apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse_otel
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: otel
      username: default
      logs:
        defaultDatabase: otel
        defaultTable: otel_logs
        otelEnabled: true
        otelVersion: latest
        timeColumn: Timestamp
        levelColumn: SeverityText
        messageColumn: Body
        traceIdColumn: TraceId
        spanIdColumn: SpanId
      traces:
        defaultDatabase: otel
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: latest
        traceIdColumn: TraceId
        spanIdColumn: SpanId
        operationNameColumn: SpanName
        parentSpanIdColumn: ParentSpanId
        serviceNameColumn: ServiceName
        durationColumn: Duration
        durationUnit: nanoseconds
        startTimeColumn: Timestamp
        tagsColumn: SpanAttributes
        serviceTagsColumn: ResourceAttributes
      tracesToLogs:
        datasourceUid: clickhouse_otel
        filterByTraceID: true
        filterBySpanID: true
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
    secureJsonData:
      password: ""
